---

- hosts: all
  become: true
  gather_facts: true

  vars:
    plone_initial_password: admin

  roles:
    - role: ../ansible-role-plone
      plone_instance_name: test_4
      plone_version: '4.3.11'
      plone_client_count: 1
    - role: ../ansible-role-plone
      plone_instance_name: test_5
      plone_version: '5.0.6'
      plone_client_base_port: 8091
      plone_client_reserved_port: 8090
      plone_zeo_port: 8190
      plone_client_count: 1

  tasks:
    # make sure plone daemons have had time to come up

    # - pause: minutes=1

    # - pip: name=httplib2

    # - name: Check to see if Plone 5 is running
    #   uri:
    #     url: http://127.0.0.1:5081/Plone
    #     method: GET
    #     status_code: 200

    # - name: Check to see if Plone 4.3.x is running
    #   uri:
    #     url: http://127.0.0.1:4081/Plone
    #     method: GET
    #     status_code: 200

    # - stat: path=/usr/local/plone-5.0/zeoserver/main.yml
    #   register: st
    # - fail: msg="copy of extra dir failed"
    #   when: not st.stat.exists

    # - name: Check to see if we copied the extra buildout file
    #   command: "ls /usr/local/plone-5.0/zeoserver/main.yml"
